ALTER TABLE oauth_code ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE oauth_code ADD COLUMN expiresat BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE oauth_code ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE oauth_code ADD COLUMN client_id VARCHAR(36) NULL;